[package]
name = "calopr"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
http = "1.2.0"
chrono = "0.4.39"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60.0", features = ["Win32_System_Console"] }
